src/Entity/Article.php
<?php

namespace App\Entity;

use App\Repository\ArticleRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ArticleRepository::class)
 */
class Article
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $TitreArt;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $DescriptionArt;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $image;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitreArt(): ?string
    {
        return $this->TitreArt;
    }

    public function setTitreArt(string $TitreArt): self
    {
        $this->TitreArt = $TitreArt;

        return $this;
    }

    public function getDescriptionArt(): ?string
    {
        return $this->DescriptionArt;
    }

    public function setDescriptionArt(string $DescriptionArt): self
    {
        $this->DescriptionArt = $DescriptionArt;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(string $image): self
    {
        $this->image = $image;

        return $this;
    }
}

templates/index/article.html.twig
{% extends 'base.html.twig' %}

{% block body %}

    <style>
    </style>
    <body class="bg-orange">
    <section class="h-96" style="background-repeat: no-repeat; background-size: cover;background-position: center center;
       background-image: url('https://i.pinimg.com/736x/e6/cf/59/e6cf59eaaa07fb81d473fdeefebdee26.jpg');">
        <div class="pt-44 lg:pt-96 flex flex-wrap flex-col justify-around">
        </div>
    </section>

    <section class="container w-10/12 mx-auto rounded-t-lg -mt-14 bg-orange1 h-14">
    </section>

    <section id="propos" class="container w-10/12 mx-auto bg-white rounded-b-lg pb-10 mb-10">
        <div class="flex flex-wrap justify-center">
            <img class="mx-auto w-64 h-64 lg:w-2/4 rounded-lg lg:h-2/4 pt-5" src='{{ get_env('DOMAIN') }}/images/{{ article.image }}' alt="">
            <div class="flex flex-col mx-auto lg:ml-5 pt-5 w-full">
                <h1 class="text-lg lg:text-2xl mx-auto">{{ article.titreArt }}</h1>
                <p class="text-lg mt-10 break-words w-10/12 lg:w-2/4 mx-auto">{{ article.descriptionArt }}</p>
            </div>
        </div>
    </section>



    </body>


{% endblock %}

templates/index/articles.html.twig
{% extends 'base.html.twig' %}

{% block body %}

    <style>
    </style>
    <body class="bg-orange">
    <section class="h-96" style="background-repeat: no-repeat; background-size: cover;background-position: center center;
       background-image: url('https://i.pinimg.com/736x/e6/cf/59/e6cf59eaaa07fb81d473fdeefebdee26.jpg');">
        <div class="pt-44 lg:pt-96 flex flex-wrap flex-col justify-around">
        </div>
    </section>

    <section class="container w-10/12 mx-auto rounded-t-lg -mt-14 bg-orange1 h-14">
    </section>

    <section id="propos" class="container w-10/12 mx-auto bg-white rounded-b-lg pb-10 mb-10">
        <h1 class="text-lg text-center pt-2">Liste de tous les articles :</h1>
        <div class="flex flex-wrap justify-center">
            {% for article in articles %}
                <div class="border-2 mt-2 border-vert4 p-5 rounded-lg">
                    <img class="w-48 h-48 rounded" src='{{ get_env('DOMAIN') }}/images/{{ article.image }}' alt="">
                    <p class="text-lg text-center my-2">{{ article.titreArt }}</p>
                    <a class="ml-7 py-1 px-2 rounded-lg border-2 border-vert3 text-vert3 hover:bg-vert3 hover:text-white "
                       href="{{ path('article',{id:article.id}) }}">
                        Détail de l'article
                    </a>
                </div>
            {% endfor %}
        </div>
    </section>



    </body>


{% endblock %}